WebApp/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using WebApp.Models;
using WebApp.Models.ViewModels;

namespace WebApp.Controllers
{
    public class ClientController : Controller
    {
        public async Task<IActionResult> Index()
        {
            IEnumerable<Client> clients = new List<Client>();
            HttpClient client = new HttpClient();

            HttpResponseMessage response = await client.GetAsync(URL.GetClients);

            if (response.StatusCode == HttpStatusCode.OK)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                clients = JsonConvert.DeserializeObject<IEnumerable<Client>>(jsonString);
                return View(clients);
            }

            return View(clients);
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            ClientVM clientVM = new ClientVM()
            {
                Client = new Client(),
            };

            if (id == null)
            {
                return View(clientVM);
            }
            else
            {
                HttpClient client = new HttpClient();
                HttpResponseMessage response = await client.GetAsync(URL.GetClientById + id);

                if (response.StatusCode == HttpStatusCode.OK)
                {
                    var jsonString = await response.Content.ReadAsStringAsync();
                    clientVM.Client = JsonConvert.DeserializeObject<Client>(jsonString);

                    if (clientVM.Client == null)
                    {
                        return NotFound();
                    }

                }
                return View(clientVM);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(ClientVM clientVM)
        {
            if (ModelState.IsValid)
            {
                if (clientVM.Client.Id == 0)
                {
                    Client client = new Client();
                    client.DocumentId = clientVM.Client.DocumentId;
                    client.Name = clientVM.Client.Name;
                    client.LastName = clientVM.Client.LastName;
                    client.Telephone = clientVM.Client.Telephone;

                    var jsonString = JsonConvert.SerializeObject(client);
                    var httpContent = new StringContent(jsonString, Encoding.UTF8, "application/json");

                    HttpClient httpclient = new HttpClient();
                    HttpResponseMessage response = await httpclient.PostAsync(URL.CreateClient, httpContent);

                    if (response.StatusCode == HttpStatusCode.NoContent)
                    {
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    var objDb = new Client();
                    HttpClient client = new HttpClient();
                    HttpResponseMessage response = await client.GetAsync(URL.GetClientById + clientVM.Client.Id);

                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        var jsonString = await response.Content.ReadAsStringAsync();
                        objDb = JsonConvert.DeserializeObject<Client>(jsonString);

                        if (objDb != null)
                        {
                            objDb.DocumentId = clientVM.Client.DocumentId;
                            objDb.Name = clientVM.Client.Name;
                            objDb.LastName = clientVM.Client.LastName;
                            objDb.Telephone = clientVM.Client.Telephone;

                            var jsonstring2 = JsonConvert.SerializeObject(objDb);
                            var httpContent = new StringContent(jsonstring2, Encoding.UTF8, "application/json");

                            HttpClient client2 = new HttpClient();
                            HttpResponseMessage response2 = await client2.PatchAsync(URL.UpdateClient + objDb.Id, httpContent);

                            if (response2.StatusCode == HttpStatusCode.NoContent)
                            {
                                return RedirectToAction("Index");
                            }
                        }
                    }
                }
            }
            return View(clientVM);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            HttpClient client = new HttpClient();
            HttpResponseMessage response = await client.GetAsync(URL.GetClientById + id);

            if (response.StatusCode == HttpStatusCode.OK)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var Client = JsonConvert.DeserializeObject<Client>(jsonString);
                return View(Client);
            }

            return View(new Client());
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int? id)
        {
            HttpClient client = new HttpClient();
            HttpResponseMessage response = await client.GetAsync(URL.GetClientById + id);

            if (response.StatusCode != HttpStatusCode.OK)
            {
                return NotFound();
            }

            HttpClient client2 = new HttpClient();
            HttpResponseMessage response2 = await client2.DeleteAsync(URL.DeleteClient + id);

            if (response2.StatusCode != HttpStatusCode.NoContent)
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }
    }
}

WebApp/Controllers/SaleController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using WebApp.Models;
using WebApp.Models.ViewModels;

namespace WebApp.Controllers
{
    public class SaleController : Controller
    {
        public async Task<IActionResult> Index()
        {
            IEnumerable<SaleVM> sales = new List<SaleVM>();
            HttpClient client = new HttpClient();

            HttpResponseMessage response = await client.GetAsync(URL.GetSales);

            if (response.StatusCode == HttpStatusCode.OK)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                sales = JsonConvert.DeserializeObject<IEnumerable<SaleVM>>(jsonString);

                return View(sales);
            }

            return View(sales);
        }

        public async Task<IActionResult> CreateSale(int? id)
        {
            IEnumerable<Product> products = new List<Product>();
            IEnumerable<Client> clients = new List<Client>();

            HttpClient client = new HttpClient();
            HttpResponseMessage response = await client.GetAsync(URL.GetProducts);
            HttpResponseMessage response2 = await client.GetAsync(URL.GetClients);


            if (response.StatusCode == HttpStatusCode.OK && response2.StatusCode == HttpStatusCode.OK)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                products = JsonConvert.DeserializeObject<List<Product>>(jsonString);
                var jsonString2 = await response2.Content.ReadAsStringAsync();
                clients = JsonConvert.DeserializeObject<List<Client>>(jsonString2);
            }

            IEnumerable<SelectListItem> ProductsDropDown = products.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.ProductId.ToString()
            });

            IEnumerable<SelectListItem> ClientsDropDown = clients.Select(i => new SelectListItem
            {
                Text = String.Concat(i.Name, " ", i.LastName),
                Value = i.Id.ToString()
            });

            ViewBag.ProductsDropDown = ProductsDropDown;
            ViewBag.ClientsDropDown = ClientsDropDown;

            CreateSaleVM saleVM = new CreateSaleVM();

            return View(saleVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSale(CreateSaleVM saleVM)
        {
            if (ModelState.IsValid)
            {

                Sale sale = new Sale();
                sale.ClientId = saleVM.ClientId;
                sale.ProductId = saleVM.ProductId;
                sale.Quantity = saleVM.Quantity;

                var jsonString = JsonConvert.SerializeObject(sale);
                var httpContent = new StringContent(jsonString, Encoding.UTF8, "application/json");

                HttpClient client = new HttpClient();
                HttpResponseMessage response = await client.PostAsync(URL.CreateSale, httpContent);

                if (response.StatusCode == HttpStatusCode.NoContent)
                {
                    return RedirectToAction("Index");
                }


            }
            return View(saleVM);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            IEnumerable<Product> products = new List<Product>();
            IEnumerable<Client> clients = new List<Client>();

            HttpClient client = new HttpClient();
            HttpResponseMessage response = await client.GetAsync(URL.GetProducts);
            HttpResponseMessage response2 = await client.GetAsync(URL.GetClients);


            if (response.StatusCode == HttpStatusCode.OK && response2.StatusCode == HttpStatusCode.OK)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                products = JsonConvert.DeserializeObject<List<Product>>(jsonString);
                var jsonString2 = await response2.Content.ReadAsStringAsync();
                clients = JsonConvert.DeserializeObject<List<Client>>(jsonString2);
            }

            IEnumerable<SelectListItem> ProductsDropDown = products.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.ProductId.ToString()
            });

            IEnumerable<SelectListItem> ClientsDropDown = clients.Select(i => new SelectListItem
            {
                Text = String.Concat(i.Name, " ", i.LastName),
                Value = i.Id.ToString()
            });

            ViewBag.ProductsDropDown = ProductsDropDown;
            ViewBag.ClientsDropDown = ClientsDropDown;

            var saleVM = new SaleVM();

            HttpResponseMessage response3 = await client.GetAsync(URL.GetSaleById + id);

            if (response3.StatusCode != HttpStatusCode.OK)
            {
                return NotFound();
            }

            var jsonString3 = await response3.Content.ReadAsStringAsync();
            saleVM = JsonConvert.DeserializeObject<SaleVM>(jsonString3);

            return View(saleVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, SaleVM saleVM)
        {
            if (ModelState.IsValid)
            {
                var saleInDb = new Sale();
                HttpClient client = new HttpClient();
                HttpResponseMessage response = await client.GetAsync(URL.GetSaleById + saleVM.SaleId);

                if (response.StatusCode == HttpStatusCode.OK)
                {
                    var jsonString = await response.Content.ReadAsStringAsync();
                    saleInDb = JsonConvert.DeserializeObject<Sale>(jsonString);

                    if (saleInDb != null)
                    {
                        saleInDb.SaleId = saleVM.SaleId;
                        saleInDb.ClientId = saleVM.ClientId;
                        saleInDb.ProductId = saleVM.ProductId;
                        saleInDb.Quantity = saleVM.Quantity;

                        var jsonString2 = JsonConvert.SerializeObject(saleInDb);
                        var httpContent = new StringContent(jsonString2, Encoding.UTF8, "application/json");

                        HttpClient client2 = new HttpClient();
                        HttpResponseMessage response2 = await client2.PatchAsync(URL.UpdateSale + saleInDb.SaleId, httpContent);

                        if (response2.StatusCode == HttpStatusCode.NoContent)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }
            }
            return View(saleVM);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            HttpClient client = new HttpClient();
            HttpResponseMessage response = await client.GetAsync(URL.GetSaleById + id);

            if (response.StatusCode == HttpStatusCode.OK)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var sale = JsonConvert.DeserializeObject<SaleVM>(jsonString);
                return View(sale);
            }

            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int? id)
        {
            HttpClient client = new HttpClient();
            HttpResponseMessage response = await client.GetAsync(URL.DeleteSale + id);

            if (response.StatusCode != HttpStatusCode.OK)
            {
                return NotFound();
            }

            HttpClient client2 = new HttpClient();
            HttpResponseMessage response2 = await client2.DeleteAsync(URL.DeleteSale + id);

            if (response2.StatusCode != HttpStatusCode.NoContent)
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }
    }
}

WebApp/Views/Shared/_IndividualProductCard.cshtml
@model WebApp.Models.Product

    <div class="col-lg-4 col-md-6 pb-4">
        <!-- Card-->
        <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
            <div class="card-body px-3 pt-3 pb-1 row">
                <div class="col-7"><label class="float-left">@Model.Name</label></div>
                <div class="col-5"><label class="float-right"><span class="text-info h5">@Model.Price</span> / sqft</label> </div>
            </div>
            <img class="card-img-top img-fluid d-block mx-auto mb-3" src="" alt="Card image cap">
            <div class="card-body p-1 px-3 row">
                <div class="col-6">
                    <span class="badge p-2 border w-100" style="background-color:lavenderblush"></span>
                </div>
                <div class="col-6 border-0">
                    <span class="badge p-2 border w-100" style="background-color:aliceblue"></span>
                </div>
                <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                    <p> </p>
                </div>
                <div class="col-12 p-1">
                    <a asp-route="@Model.ProductId" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
                </div>
            </div>
        </div>
    </div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sophos Prueba</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="Index">Ventas</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>